<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.1.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Contact/Buy Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U2564' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U2682' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Cell Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Cell Phone\' is required.'
			)
		),
		'custom_U2699' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Home Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Home Address\' is required.'
			)
		),
		'custom_U2715' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'City',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'City\' is required.'
			)
		),
		'custom_U2731' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'State',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'State\' is required.'
			)
		),
		'custom_U2747' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Zip code',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Zip code\' is required.'
			)
		),
		'custom_U2763' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Country',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Country\' is required.'
			)
		),
		'custom_U2779' => array(
			'order' => 11,
			'type' => 'checkbox',
			'label' => 'By checking this box you agree that Tony\'s Baloney™ is not responsible for the loss Boloney and/or life by eating it',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'By checking this box you agree that Tony\'s Baloney™ is not responsible for the loss Boloney and/or life by eating it\' is required.'
			)
		),
		'custom_U2853' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Card Number',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Card Number\' is required.'
			)
		),
		'custom_U2869' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Baloney Types  and Amount',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Baloney Types  and Amount\' is required.'
			)
		)
	)
);

process_form($form);
?>
